# Generated by Django 3.0.7 on 2020-08-10 09:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0002_auto_20200810_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='NewArticle',
        ),
        migrations.AlterModelTable(
            name='newarticle',
            table='new_article',
        ),
    ]
