# Generated by Django 3.0.7 on 2020-08-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200810_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('img', models.ImageField(upload_to='img')),
            ],
            options={
                'db_table': 'ImageStore',
            },
        ),
    ]
